yarnPath: .yarn/releases/yarn-3.2.1.cjs
packageExtensions:
  "prosemirror-state@*":
    dependencies:
      "prosemirror-view": "*"
  "@trustlane/schematics@*":
    dependencies:
      "@schematics/angular": "*"
  "@nrwl/devkit@*":
    dependencies:
      "@angular-devkit/architect": "*"
  "@angular-eslint/schematics@*":
    dependencies:
      "@angular-devkit/schematics": "*"
      "@angular-devkit/core": "*"
  "@compodoc/compodoc@*":
    dependencies:
      "typescript": "*"
  "@storybook/angular@*":
    dependencies:
      "@angular-devkit/architect": "*"
      "@angular-devkit/core": "*"
  "@storybook/ui@*":
    dependencies:
      "react-dom": "*"
      "react": "*"
  "@storybook/builder-webpack5@*":
    dependencies:
      "react-dom": "*"
      "react": "*"
  "@storybook/addon-docs@*":
    dependencies:
      "@babel/core": "*"
